### ISSUE TITLE
Фруктовая лавка.

### ISSUE THREAD

**Issue by milkina** [AlexeyTsukanov/Lessons#18]
1. Добавить  eqauls, toString
2. printManufacturerInfo - добавить мод. доступа.
3. Сначала пишите геттеры и сеттеры , потом все ост. методы.
4. метод, возвращающий стоимость фрукта, должен учитывать вес фрукта

**Comment by AlexeyTsukanov** [comment]
4. Он учитывает вес фрукта.

**Comment by milkina** [comment]
В Fruit тоже добавьте equals и toString. И пусть они вызываются из наследников.

**Comment by milkina** [comment]
weight не учитывается в классах наследниках в toString, equals.  Добавьте его
